# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'projectOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectOC
pod 'IQKeyboardManager'

pod 'AFNetworking'
pod 'MBProgressHUD'
#pod 'MJRefresh'
pod 'SDWebImage'

pod 'Charts'

pod 'MQTTClient'

pod 'MQTTClient/Websocket'
pod 'SocketRocket'

pod 'PGDatePicker'
#websocket 方式连接
#pod 'MQTTClient/MinL'
#pod 'MQTTClient/ManagerL'
#pod 'MQTTClient/WebsocketL'

#wifi 物联网
pod 'CocoaAsyncSocket'

##############################




  target 'projectOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
